<?php
include_once("sa-dbh.inc.php");
include_once("sa-head.php");
include_once("sa-sidebar.php");
include_once("sa-navbar.php");

$table = "laws";
$result = nextId($con, $table);
$nextId = $result;

ob_start(); // All output generated by the included file will be stored in a buffer instead of being sent directly to the browser.
include "../../includes/main/alerts.inc.php";
$alert = ob_get_clean(); // Retrieves the contents of the output buffer, clears the buffer, and returns the contents as a string.

$options_act = array(
    "Motor Traffic (AMENDMENT) Act, No. 8 of 2009" => "Motor Traffic (AMENDMENT) Act, No. 8 of 2009"
);

$options_type = array(
    "Fine" => "Fine",
    "Court" => "Court",
    "Other" => "Other"
);
?>

<section class="home-section">

    <div class="content">
        <div class="title-bar">
            <div class="heading">
                <h1>Add New Traffic Violation Law</h1>
            </div>
        </div>
        <div class="container">
            <form method="post" action="../../includes/system-admin/law-add.inc.php">
                <table class="form form-law">
                    <tr>
                        <td><label>Violation Id</label></td>
                        <td><input type="text" name="id" id="id" class="disabled" disabled value=<?php echo $nextId; ?>></td>
                    </tr>
                    <tr>
                        <td><label>Act</label></td>
                        <td>
                            <select name="act" id="act">
                                <?php
                                foreach ($options_act as $option) {
                                    echo "<option value='" . $option . "'>" . $option . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Part</label></td>
                        <td><input type="number" name="part_number" id="part_number" min="1"></td>
                    </tr>
                    <tr>
                        <td><label>Chapter</label></td>
                        <td><input type="number" name="chapter_number" id="chapter_number" min="1"></td>
                    </tr>
                    <tr>
                        <td><label>Section</label></td>
                        <td><input type="number" name="section_number" id="section_number" min="1"></td>
                    </tr>
                    <tr>
                        <td><label>Title</label></td>
                        <td><input type="text" name="title" id="title"></td>
                    </tr>
                    <tr>
                        <td><label>Law</label></td>
                        <td><textarea name="law_text" id="law_text" cols="50" rows="7"></textarea></td>
                    </tr>
                    <tr>
                        <td><label>Law type</label></td>
                        <td>
                            <select name="law_type" id="law_type">
                                <?php
                                foreach ($options_type as $option) {
                                    echo "<option value='" . $option . "'>" . $option . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Fine</label></td>
                        <td>
                            <div class="currency">
                                <input class="currency-symbol disabled" disabled value="Rs"></input>
                                <input type="number" name="fine_amount" id="fine_amount" class="currency-input" min="0">
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Points</label></td>
                        <td><input type="number" name="points_deducted" id="points_deducted" min="0" max="24"></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="btn-group">
                                <a href="law-view.php">
                                    <div class="btn btn-secondary">Cancel</div>
                                </a>
                                <button class="btn btn-primary" type="submit" name="submit">Save</button>
                                <?php echo $alert; ?>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

</section>