<?php
include_once("sa-dbh.inc.php");
include_once("sa-head.php");
include_once("sa-sidebar.php");
include_once("sa-navbar.php");

$table = "police_station_admin";
$result = nextId($con, $table);
$nextId = $result;

ob_start(); // All output generated by the included file will be stored in a buffer instead of being sent directly to the browser.
include "../../includes/main/alerts.inc.php";
$alert = ob_get_clean(); // Retrieves the contents of the output buffer, clears the buffer, and returns the contents as a string.

$options_province = array(
    "Western Province" => "Western Province",
    "Central Province" => "Central Province",
    "North Central Province" => "North Central Province",
    "Northern Province" => "Northern Province",
    "Eastern Province" => "Eastern Province",
    "North Western Province" => "North Western Province",
    "Southern Province" => "Southern Province",
    "Uva Province" => "Uva Province",
    "Sabaragamuwa Province" => "Sabaragamuwa Province"
);

$options_district = array(
    "Colombo" => "Colombo",
    "Gampaha" => "Gampaha",
    "Kalutara" => "Kalutara",
    "Kandy" => "Kandy",
    "Matale" => "Matale",
    "Nuwara Eliya" => "Nuwara Eliya",
    "Galle" => "Galle",
    "Matara" => "Matara",
    "Hambantota" => "Hambantota",
    "Jaffna" => "Jaffna",
    "Kilinochchi" => "Kilinochchi",
    "Mannar" => "Mannar",
    "Vavuniya" => "Vavuniya",
    "Mullaitivu" => "Mullaitivu",
    "Batticaloa" => "Batticaloa",
    "Ampara" => "Ampara",
    "Trincomalee" => "Trincomalee",
    "Kurunegala" => "Kurunegala",
    "Puttalam" => "Puttalam",
    "Anuradhapura" => "Anuradhapura",
    "Polonnaruwa" => "Polonnaruwa",
    "Badulla" => "Badulla",
    "Moneragala" => "Moneragala",
    "Ratnapura" => "Ratnapura",
    "Kegalle" => "Kegalle"
);

$options_court_name = array(
    "High Court Ambilipitiya" => "High Court Ambilipitiya",
    "High Court Ampara" => "High Court Ampara",
    "High Court Anuradhapura" => "High Court Anuradhapura",
    "High Court Avissawella" => "High Court Avissawella",
    "High Court Badulla" => "High Court Badulla",
    "High Court Balapitiya" => "High Court Balapitiya",
    "High Court Batticaloa" => "High Court Batticaloa",
    "High Court Chilaw" => "High Court Chilaw",
    "High Court Colombo" => "High Court Colombo",
    "High Court Galle" => "High Court Galle",
    "High Court Gampaha" => "High Court Gampaha",
    "High Court Hambantota" => "High Court Hambantota",
    "High Court Jaffna" => "High Court Jaffna",
    "High Court Kalmunai" => "High Court Kalmunai",
    "High Court Kandy" => "High Court Kandy",
    "High Court Kegalle" => "High Court Kegalle",
    "High Court Kurunegala" => "High Court Kurunegala",
    "High Court Matara" => "High Court Matara",
    "High Court Negombo" => "High Court Negombo",
    "High Court Panadura" => "High Court Panadura",
    "High Court Polonnaruwa" => "High Court Polonnaruwa",
    "High Court Puttalam" => "High Court Puttalam",
    "High Court Ratnapura" => "High Court Ratnapura",
    "High Court Trincomalee" => "High Court Trincomalee",
    "High Court Vavuniya" => "High Court Vavuniya",
    "High Court Welikada" => "High Court Welikada",
    "District Court Akkaraipattu" => "District Court Akkaraipattu",
    "District Court Ampara" => "District Court Ampara",
    "District Court Anuradhapura" => "District Court Anuradhapura",
    "District Court Attanagalla" => "District Court Attanagalla",
    "District Court Avissawella" => "District Court Avissawella",
    "District Court Badulla" => "District Court Badulla",
    "District Court Balapitiya" => "District Court Balapitiya",
    "District Court Bandarawela" => "District Court Bandarawela",
    "District Court Batticaloa" => "District Court Batticaloa",
    "District Court Chavakachcheri" => "District Court Chavakachcheri",
    "District Court Chilaw" => "District Court Chilaw",
    "District Court Colombo" => "District Court Colombo",
    "District Court Elpitiya" => "District Court Elpitiya",
    "District Court Embilipitiya" => "District Court Embilipitiya",
    "District Court Galle" => "District Court Galle",
    "District Court Gampaha" => "District Court Gampaha",
    "District Court Gampola" => "District Court Gampola",
    "District Court Hambantota" => "District Court Hambantota",
    "District Court Hatton" => "District Court Hatton",
    "District Court Homagama" => "District Court Homagama",
    "District Court Horana" => "District Court Horana",
    "District Court Jaffna" => "District Court Jaffna",
    "District Court Kalmunai" => "District Court Kalmunai",
    "District Court Kalutara" => "District Court Kalutara",
    "District Court Kandy" => "District Court Kandy",
    "District Court Kayts" => "District Court Kayts",
    "District Court Kegalle" => "District Court Kegalle",
    "District Court Kuliyapitiya" => "District Court Kuliyapitiya",
    "District Court Kurunegala" => "District Court Kurunegala",
    "District Court Maho" => "District Court Maho",
    "District Court Mallakam" => "District Court Mallakam",
    "District Court Mannar" => "District Court Mannar",
    "District Court Marawila" => "District Court Marawila",
    "District Court Matale" => "District Court Matale",
    "District Court Matara" => "District Court Matara",
    "District Court Matugama" => "District Court Matugama",
    "District Court Moneragala" => "District Court Moneragala",
    "District Court Moratuwa" => "District Court Moratuwa",
    "District Court Mount Lavinia" => "District Court Mount Lavinia",
    "District Court Mullativu" => "District Court Mullativu",
    "District Court Negombo" => "District Court Negombo",
    "District Court Nuwara Eliya" => "District Court Nuwara Eliya",
    "District Court Panadura" => "District Court Panadura",
    "District Court Point Pedro" => "District Court Point Pedro",
    "District Court Polonnaruwa" => "District Court Polonnaruwa"
);
?>

<section class="home-section">

    <div class="content">

        <div class="title-bar">
            <div class="heading">
                <h1>Add New Police Station Admin</h1>
            </div>
        </div>

        <div class="container">
            <form method="post" action="../../includes/system-admin/psa-add.inc.php">
                <table class="form form-psa">
                    <tr>
                        <td><label>Police Station Id</label></td>
                        <td><input type="text" name="id" id="id" class="disabled" disabled value=<?php echo $nextId; ?>></td>

                    </tr>
                    <tr>
                        <td><label>Province</label></td>
                        <td>
                            <input class="select" name="province" id="select-province" value="<?php echo array_key_first($options_province); ?>" style="width: 240px;">
                            <datalist id="province">
                                <?php
                                foreach ($options_province as $option) {
                                    echo "<option value='" . $option . "'>" . $option . "</option>";
                                }
                                ?>
                            </datalist>
                        </td>
                    </tr>
                    <tr>
                        <td><label>District</label></td>
                        <td>
                            <input class="select" name="district" id="select-district" value="<?php echo array_key_first($options_district); ?>" style="width: 170px;">
                            <datalist id="district">
                                <?php
                                foreach ($options_district as $option) {
                                    echo "<option value='" . $option . "'>" . $option . "</option>";
                                }
                                ?>
                            </datalist>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Police Station</label></td>
                        <td><input type="text" name="police_station" id="police_station"></td>
                    </tr>
                    <tr>
                        <td><label>Email Address</label></td>
                        <td><input type="text" name="email" id="email"></td>
                    </tr>

                    <tr>
                        <td><label>Court Name</label></td>
                        <td>
                            <input class="select" name="court_name" id="select-court" value="<?php echo array_key_first($options_court_name); ?>" style="width: 280px;">
                            <datalist id="court">
                                <?php
                                foreach ($options_court_name as $option) {
                                    echo "<option value='" . $option . "'>" . $option . "</option>";
                                }
                                ?>
                            </datalist>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="btn-group">
                                <a href="psa-view.php">
                                    <div class="btn btn-secondary">Cancel</div>
                                </a>
                                <button class="btn btn-primary" type="submit" name="submit">Save</button>
                                <?php echo $alert; ?>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>

    </div>

</section>

<script src="../../public/js/datalist-psa.js"></script>