<?php
include_once("sa-dbh.inc.php");
include_once("sa-head.php");
include_once("sa-sidebar.php");
include_once("sa-navbar.php");
require("delete-dialog.php");

ob_start(); // All output generated by the included file will be stored in a buffer instead of being sent directly to the browser.
include "../../includes/main/alerts.inc.php";
$alert = ob_get_clean(); // Retrieves the contents of the output buffer, clears the buffer, and returns the contents as a string.

$options_column = array(
    "id" => "Id",
    "province" => "Province",
    "district" => "District",
    "police_station" => "Police station",
    "email" => "Email",
    "court_name" => "Court name",
    "added_by" => "Added by",
    "created_at" => "Created at",
    "latest_update_by" => "Latest update by",
    "latest_update_at" => "Latest update at"
);

$options_province = array(
    "Western Province" => "Western Province",
    "Central Province" => "Central Province",
    "North Central Province" => "North Central Province",
    "Northern Province" => "Northern Province",
    "Eastern Province" => "Eastern Province",
    "North Western Province" => "North Western Province",
    "Southern Province" => "Southern Province",
    "Uva Province" => "Uva Province",
    "Sabaragamuwa Province" => "Sabaragamuwa Province"
);

$options_district = array(
    "Colombo" => "Colombo",
    "Gampaha" => "Gampaha",
    "Kalutara" => "Kalutara",
    "Kandy" => "Kandy",
    "Matale" => "Matale",
    "Nuwara Eliya" => "Nuwara Eliya",
    "Galle" => "Galle",
    "Matara" => "Matara",
    "Hambantota" => "Hambantota",
    "Jaffna" => "Jaffna",
    "Kilinochchi" => "Kilinochchi",
    "Mannar" => "Mannar",
    "Vavuniya" => "Vavuniya",
    "Mullaitivu" => "Mullaitivu",
    "Batticaloa" => "Batticaloa",
    "Ampara" => "Ampara",
    "Trincomalee" => "Trincomalee",
    "Kurunegala" => "Kurunegala",
    "Puttalam" => "Puttalam",
    "Anuradhapura" => "Anuradhapura",
    "Polonnaruwa" => "Polonnaruwa",
    "Badulla" => "Badulla",
    "Moneragala" => "Moneragala",
    "Ratnapura" => "Ratnapura",
    "Kegalle" => "Kegalle"
);

$options_court_name = array(
    "High Court Ambilipitiya" => "High Court Ambilipitiya",
    "High Court Ampara" => "High Court Ampara",
    "High Court Anuradhapura" => "High Court Anuradhapura",
    "High Court Avissawella" => "High Court Avissawella",
    "High Court Badulla" => "High Court Badulla",
    "High Court Balapitiya" => "High Court Balapitiya",
    "High Court Batticaloa" => "High Court Batticaloa",
    "High Court Chilaw" => "High Court Chilaw",
    "High Court Colombo" => "High Court Colombo",
    "High Court Galle" => "High Court Galle",
    "High Court Gampaha" => "High Court Gampaha",
    "High Court Hambantota" => "High Court Hambantota",
    "High Court Jaffna" => "High Court Jaffna",
    "High Court Kalmunai" => "High Court Kalmunai",
    "High Court Kandy" => "High Court Kandy",
    "High Court Kegalle" => "High Court Kegalle",
    "High Court Kurunegala" => "High Court Kurunegala",
    "High Court Matara" => "High Court Matara",
    "High Court Negombo" => "High Court Negombo",
    "High Court Panadura" => "High Court Panadura",
    "High Court Polonnaruwa" => "High Court Polonnaruwa",
    "High Court Puttalam" => "High Court Puttalam",
    "High Court Ratnapura" => "High Court Ratnapura",
    "High Court Trincomalee" => "High Court Trincomalee",
    "High Court Vavuniya" => "High Court Vavuniya",
    "High Court Welikada" => "High Court Welikada",
    "District Court Akkaraipattu" => "District Court Akkaraipattu",
    "District Court Ampara" => "District Court Ampara",
    "District Court Anuradhapura" => "District Court Anuradhapura",
    "District Court Attanagalla" => "District Court Attanagalla",
    "District Court Avissawella" => "District Court Avissawella",
    "District Court Badulla" => "District Court Badulla",
    "District Court Balapitiya" => "District Court Balapitiya",
    "District Court Bandarawela" => "District Court Bandarawela",
    "District Court Batticaloa" => "District Court Batticaloa",
    "District Court Chavakachcheri" => "District Court Chavakachcheri",
    "District Court Chilaw" => "District Court Chilaw",
    "District Court Colombo" => "District Court Colombo",
    "District Court Elpitiya" => "District Court Elpitiya",
    "District Court Embilipitiya" => "District Court Embilipitiya",
    "District Court Galle" => "District Court Galle",
    "District Court Gampaha" => "District Court Gampaha",
    "District Court Gampola" => "District Court Gampola",
    "District Court Hambantota" => "District Court Hambantota",
    "District Court Hatton" => "District Court Hatton",
    "District Court Homagama" => "District Court Homagama",
    "District Court Horana" => "District Court Horana",
    "District Court Jaffna" => "District Court Jaffna",
    "District Court Kalmunai" => "District Court Kalmunai",
    "District Court Kalutara" => "District Court Kalutara",
    "District Court Kandy" => "District Court Kandy",
    "District Court Kayts" => "District Court Kayts",
    "District Court Kegalle" => "District Court Kegalle",
    "District Court Kuliyapitiya" => "District Court Kuliyapitiya",
    "District Court Kurunegala" => "District Court Kurunegala",
    "District Court Maho" => "District Court Maho",
    "District Court Mallakam" => "District Court Mallakam",
    "District Court Mannar" => "District Court Mannar",
    "District Court Marawila" => "District Court Marawila",
    "District Court Matale" => "District Court Matale",
    "District Court Matara" => "District Court Matara",
    "District Court Matugama" => "District Court Matugama",
    "District Court Moneragala" => "District Court Moneragala",
    "District Court Moratuwa" => "District Court Moratuwa",
    "District Court Mount Lavinia" => "District Court Mount Lavinia",
    "District Court Mullativu" => "District Court Mullativu",
    "District Court Negombo" => "District Court Negombo",
    "District Court Nuwara Eliya" => "District Court Nuwara Eliya",
    "District Court Panadura" => "District Court Panadura",
    "District Court Point Pedro" => "District Court Point Pedro",
    "District Court Polonnaruwa" => "District Court Polonnaruwa"
);
?>

<section class="home-section">

    <div class="content">

        <div class="title-bar">
            <div class="heading">
                <h1>Police Station Admins</h1>
            </div>
            <div class="btn-group">
                <!-- <div class="quick-search">
                    <input type="text" name="quick-search" id="quick-search" placeholder="Quick Search...">
                </div> -->
                <a href="psa-add.php"><button class="btn btn-primary">Add New</button></a>
            </div>
        </div>

        <div class="container">
            <form method="get">
                <div class="search-by">
                    <div class="search-by-left">
                        <span>Search by</span>
                        <select name="column" id="column" onchange="changeInputType()">
                            <?php foreach ($options_column as $value => $label) {
                                $selected = '';
                                if (isset($_GET['column']) && $_GET['column'] == $value) {
                                    $selected = 'selected';
                                }
                                echo "<option value='$value' $selected>$label</option>";
                            } ?>
                        </select>
                        <span id="search-input-container">
                            <?php
                            $search_term = isset($_GET['search']) ? htmlspecialchars($_GET['search']) : '';
                            $search_column = isset($_GET['column']) ? $_GET['column'] : '';

                            if ($search_column === "province") {
                                echo "<select name='search' id='search'>";
                                foreach ($options_province as $option) {
                                    echo "<option value='" . $option . "' " . (($search_term ===  $option) ? "selected" : "") . ">" . $option . "</option>";
                                }
                                echo "</select>";
                            } else if ($search_column === "district") {
                                echo "<select name='search' id='search'>";
                                foreach ($options_district as $option) {
                                    echo "<option value='" . $option . "' " . (($search_term ===  $option) ? "selected" : "") . ">" . $option . "</option>";
                                }
                                echo "</select>";
                            } else if ($search_column === "court_name") {
                                echo "<select name='search' id='search'>";
                                foreach ($options_court_name as $option) {
                                    echo "<option value='" . $option . "' " . (($search_term ===  $option) ? "selected" : "") . ">" . $option . "</option>";
                                }
                                echo "</select>";
                            } else if ($search_column === "created_at" || $search_column === "latest_update_at") {
                                echo "<input type='date' name='search' id='search' value='$search_term'>";
                            } else if ($search_column === "id" || $search_column === "added_by" || $search_column === "latest_update_by") {
                                echo "<input type='number' name='search' id='search' value='$search_term'>";
                            } else if ($search_column === "police_station" || $search_column === "email") {
                                echo "<input type='text' name='search' id='search' value='$search_term'>";
                            } else {
                                echo "<input type='number' name='search' id='search' value='$search_term'>";
                            }
                            ?>
                        </span>
                    </div>
                    <div class="search-by-right btn-group">
                        <div>
                            <button class="btn btn-secondary" type="button" onclick="location.href='?page=1'">Clear</button>
                        </div>
                        <div>
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="container">
            <?php
            include("../../includes/system-admin/psa-view.inc.php");

            // Display records
            if ($result->num_rows > 0) {
            ?>
                <div class="table">
                    <table>
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Province</th>
                                <th>District</th>
                                <th>Police station</th>
                                <th>Email</th>
                                <th>Court name</th>
                                <th>Created at</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php while ($row = mysqli_fetch_assoc($result)) { ?>
                                <tr>
                                    <td><?php echo $row['id']; ?></td>
                                    <td><?php echo $row['province']; ?></td>
                                    <td><?php echo $row['district']; ?></td>
                                    <td><?php echo $row['name']; ?></td>
                                    <td><?php echo $row['email']; ?></td>
                                    <td><?php echo $row['court_name']; ?></td>
                                    <td><?php echo $row['created_at']; ?></td>
                                    <td><a href="psa-details.php?id=<?php echo $row['id']; ?>"><i class='bx bx-detail'></i></a></td>
                                    <td><a href="psa-edit.php?id=<?php echo $row['id']; ?>"><i class='bx bxs-edit'></i></a></td>
                                    <td>
                                        <a href="../../includes/system-admin/psa-delete.inc.php?id=<?php echo $row['id']; ?>" onclick="showDeleteDialog(this); return false;">
                                            <i class="bx bx-trash delBtn"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <?php echo $alert; ?>
                </div>
            <?php
            }
            ?>

            <?php include("pagination.php"); ?>

        </div>

    </div>

</section>

<script src="../../public/js/search-by-psa.js"></script>
<script src="../../public/js/delete-dialog.js"></script>